const query = `CREATE TABLE IF NOT EXISTS todo(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATE NOT NULL DEFAULT CURRENT_DATE + INTERVAL '1 day',
  createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
  updatedAt DATE NOT NULL DEFAULT CURRENT_DATE
);`;
module.exports = query;
